### 1) Signup
POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "name": "Beltrano",
    "email": "beltrano2@gmail.com",
    "password": "abc123"
}

### 2) Login
POST http://localhost:3003/users/login
Content-Type: application/json



{
    "email": "astrodev@gmail.com",
    "password": "bananinha"
}

### 3) Get users
GET http://localhost:3003/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJiOWI3ZWU4LWFlNGItNGJkMS05YmQ2LWU3ZTIxNTk0Mzk5YiIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2Mzc3NTk0NSwiZXhwIjoxNjYzODYyMzQ1fQ.T-3kzPoA0gZRLPSSulZfSUqGeKvdDt9hXiaZ94ynfNs

### 3) Delete user
DELETE http://localhost:3003/users/0b3d9d2f-c452-46b4-8a0c-1426d0b45196
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJiOWI3ZWU4LWFlNGItNGJkMS05YmQ2LWU3ZTIxNTk0Mzk5YiIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2Mzc3NTk0NSwiZXhwIjoxNjYzODYyMzQ1fQ.T-3kzPoA0gZRLPSSulZfSUqGeKvdDt9hXiaZ94ynfNs

### 4) Edit user
PUT http://localhost:3003/users/bb9b7ee8-ae4b-4bd1-9bd6-e7e21594399b
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJiOWI3ZWU4LWFlNGItNGJkMS05YmQ2LWU3ZTIxNTk0Mzk5YiIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2Mzc3NTk0NSwiZXhwIjoxNjYzODYyMzQ1fQ.T-3kzPoA0gZRLPSSulZfSUqGeKvdDt9hXiaZ94ynfNs
Content-Type: application/json

{
    "name": "Astrodev3"
}